Support copy from right in timetable editor
ibi-group/datatools-ui pull request #1013
Opened 2024-05-01 10:26 UTC by miles-grant-ibigroup

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Timetable editor has a cool keyboard shortcut to copy from left/top, but nothing to copy from right! We add shift+l to do this, mirroring shift+'.

Please test thoroughly I could only come up with so many edge cases. Tempted to add a new e2e case

2024-05-20 18:04 UTC, josh-willis-arcadis approved these changes

2024-09-24 18:03 UTC, binh-dam-ibigroup commented on lib/editor/util/timetable.js
> +  modify: ['#', 'n', 'c', 'SHIFT:+:\'', 'SHIFT:+:l', 'SHIFT:+:;']
Is that me, or was copy-from-left SHIFT+Apostrophy? (SHIFT+semicolon does nothing.)

2024-09-24 18:16 UTC, binh-dam-ibigroup requested changes
Add null checks and a check to avoid copying time into a non-time cell.

2024-09-24 18:16 UTC, binh-dam-ibigroup commented on lib/editor/components/timetable/TimetableGrid.js
> +        if (evt.shiftKey && !activeCell && isTimeFormat(adjacentCol.type)) {
Need to check that `adjacentCol` is defined (see console error), and that check needs to be added for copy-from-left.

2024-09-24 18:16 UTC, binh-dam-ibigroup commented on lib/editor/components/timetable/TimetableGrid.js
> +        if (evt.shiftKey && !activeCell && isTimeFormat(adjacentCol.type)) {
I think there should also be an `isTimeFormat` check for the focused cell. (We probably don't want to copy a time value into a non-time cell, but this is possible, as written, from the first time cell into the trip short name cell).

2024-09-24 18:16 UTC, binh-dam-ibigroup commented on lib/editor/components/timetable/TimetableGrid.js
> +        if (evt.shiftKey && !activeCell && isTimeFormat(adjacentCol.type)) {
There is a caveat that the adjacent cells must be visible for the copy operations to complete, but that is not blocking for this PR.

2024-09-24 18:16 UTC, binh-dam-ibigroup commented on lib/editor/util/timetable.js
> +  modify: ['#', 'n', 'c', 'SHIFT:+:\'', 'SHIFT:+:l', 'SHIFT:+:;']
> Is that me, or was copy-from-left SHIFT+Apostrophy? (SHIFT+semicolon does nothing.)

Disregard^^

2024-12-31 13:48 UTC, miles-grant-ibigroup commented on lib/editor/components/timetable/TimetableGrid.js
> +        if (evt.shiftKey && !activeCell && isTimeFormat(adjacentCol.type)) {
Good ideas! Really this entire file should be refactored but these are great suggestions for now1

2025-01-06 19:52 UTC, binh-dam-ibigroup approved these changes
Thanks for the changes

2025-01-07 09:31 UTC, merged