fix: define and document MAP_BASE_URL to prevent gray maps
ibi-group/datatools-ui pull request #1016
Opened 2024-07-03 19:50 UTC by Aletor93

### Checklist

- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [ ] All tests and CI builds passing

### Description

The maps are gray when we start the application with this commit id ae16265b8041d32a45964bb0d208d8eb6cf5a347. 
A functional fix was suggested by a maintainer. My suggestion is to add it to the default environment variables template.

Fix suggestion: https://github.com/ibi-group/datatools-ui/issues/983#issuecomment-1922182079
Related issue: https://github.com/ibi-group/datatools-ui/issues/983

2024-07-11 18:46 UTC, miles-grant-ibigroup approved these changes
This looks great thanks for these changes!

2024-07-16 14:45 UTC, binh-dam-ibigroup approved these changes
Could you just fix the comment for the `MAP_BASE_URL` parameter, please?

2024-07-16 14:45 UTC, binh-dam-ibigroup commented on configurations/default/env.yml.tmp
> +MAP_BASE_URL: http://tile.openstreetmap.org/{z}/{x}/{y}.png # Keep it until a fix or maps are gray
The comment seems incomplete. Could you reword it, please?

2024-07-16 14:46 UTC, binh-dam-ibigroup requested changes
Could you just fix the comment for the MAP_BASE_URL parameter, please?

2024-07-29 08:03 UTC, Aletor93 commented
Sorry for the delay, I've commented MAP_BASE_URL.

2024-07-29 12:36 UTC, binh-dam-ibigroup approved these changes

2024-07-29 12:47 UTC, merged