remove project-wide deployment settings
ibi-group/datatools-ui pull request #1023
Opened 2024-12-13 16:50 UTC by miles-grant-ibigroup

There were some project wide deployment settings that were causing more harm than good given how datatools is used these days! These settings are removed in this PR

2024-12-16 18:39 UTC, binh-dam-ibigroup requested changes
Remove dead resources as indicated.

2024-12-16 18:39 UTC, binh-dam-ibigroup commented on lib/manager/components/ProjectSettings.js
> -      activeSettingsPanel,
Remove this prop from type `Props`, and remove the corresponding passed prop from `ProjectViewer` line 268.

2024-12-16 18:39 UTC, binh-dam-ibigroup commented on lib/manager/components/deployment/DeploymentSettings.js
> -  messages = getComponentMessages('DeploymentSettings')
Remove the `DeploymentSettings` section from the language files (it is unused).

2024-12-17 15:20 UTC, miles-grant-ibigroup commented
Good catches! Addressed

2024-12-17 15:24 UTC, binh-dam-ibigroup commented on lib/manager/components/ProjectSettings.js
> -  messages = getComponentMessages('ProjectSettings')
Oops I just saw this one, it looks like `ProjectSettings` can be removed from the language files too!

2024-12-17 15:38 UTC, binh-dam-ibigroup approved these changes
Nice to see the legacy stuff go!

2024-12-19 19:51 UTC, josh-willis-arcadis approved these changes
LGTM!

2024-12-19 21:17 UTC, merged