Lazy-load server data with ec2 instance info
ibi-group/datatools-ui pull request #615
Opened 2020-10-03 05:20 UTC by evansiroky

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

This PR changes the way data is loaded for the ServerSettings admin component. Whenever a panel showing the details about a server is expanded, the UI will now make a call to a new endpoint in datatools-server to load the full information about the server which could include data about ec2 instances. This is done to avoid making unnecessary calls to AWS until that data is actually needed.

This PR requires using the code in https://github.com/ibi-group/datatools-server/pull/343.

2020-10-05 20:25 UTC, landonreed commented on lib/admin/reducers/servers.js
> +          data: { [serverIdx]: { $set: action.payload } }
Not necessarily needed, but seems like an opportunity to reuse the serverData variable?

2020-10-05 20:28 UTC, landonreed commented on lib/admin/components/ServerSettings.js
>    _onSaveServer = (index: number) => this.props.updateServer(this.state.otpServers[index])
What happens if a server is expanded, you apply updates, and click save? Are the server ec2 instances no longer shown?

2020-10-05 20:28 UTC, landonreed requested changes
One minor comment, one that probably needs addressing.

2020-10-06 22:16 UTC, binh-dam-ibigroup approved these changes
Subject to @landonreed's comment about refetching EC2 instances on an expanded server panel.

2020-10-06 22:54 UTC, evansiroky commented
Good catch. I just pushed a change that addresses this.

2020-10-08 15:00 UTC, landonreed approved these changes

2020-10-09 05:45 UTC, merged