Handle new gtfs-lib response for encoded polylines
ibi-group/datatools-ui pull request #630
Opened 2020-11-30 20:54 UTC by landonreed

### Checklist

- [ ] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [ ] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [ ] The description lists all applicable issues this PR seeks to resolve
- [ ] The description lists any configuration setting(s) that differ from the default settings
- [ ] All tests and CI builds passing

### Description

fix #627. Alternative approach to #628. This works with changes from https://github.com/conveyal/gtfs-lib/pull/297

2020-11-30 22:32 UTC, binh-dam-ibigroup reviewed
Please address merge conflicts and build failures...

2020-12-01 00:51 UTC, evansiroky commented on lib/editor/actions/tripPattern.js
> +      .then(data => dispatch(receiveGTFSEntities({namespace, component: 'pattern', data, editor: true, replaceNew: true})))
Line too long.

2020-12-01 00:54 UTC, evansiroky requested changes
- Fix failing travis build
- Fix merge conflicts

2020-12-02 17:06 UTC, evansiroky commented on lib/editor/actions/tripPattern.js
> +    shapes_as_polylines (limit: -1) {
Is `limit` needed here?

2020-12-02 17:26 UTC, evansiroky approved these changes
Approved, pending the changes in https://github.com/conveyal/gtfs-lib/pull/297 percolating it's way through the pipeline.

2020-12-03 16:59 UTC, binh-dam-ibigroup approved these changes
Looks good and seems to be working after regenerating snapshots.

2020-12-03 16:59 UTC, binh-dam-ibigroup commented on lib/editor/actions/tripPattern.js
> +import {showEditorModal} from './editor'
abc order

2020-12-03 19:26 UTC, landonreed commented
Marked as blocked until datatools-server has the latest gtfs-lib release.

2020-12-04 17:38 UTC, evansiroky commented
Something I just noticed... the Feed Version map still uses the raw GTFS shapes attributes to find the shapes: https://github.com/ibi-group/datatools-ui/blob/93a7dec276d2a2598a1197f468893f0c24d7fd0f/lib/gtfs/actions/shapes.js#L24-L48

Can this be updated too?

2020-12-22 16:42 UTC, merged