fix(saveEntity, saveTripsForCalendar): Resolve missing defaults with GTFS spec changes
ibi-group/datatools-ui pull request #720
Opened 2021-09-22 13:58 UTC by philip-cline

Closes #716, #717. New fields added with the changes to the GTFS spec (https://github.com/ibi-group/datatools-ui/pull/668) are missing from old feeds when a GTFS entity is saved, producing a `field missing from JSON object` error. Fixed by providing default values which are overridden if the feed provides its own values for the new fields. 

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

2021-09-22 15:00 UTC, binh-dam-ibigroup requested changes
Getting in the right direction. The remaining gap is to initialize the feed email and URL fields in UI. See also other comments.

2021-09-22 15:09 UTC, philip-cline commented on lib/editor/actions/active.js
> +
This was an automatic format

2021-09-22 16:27 UTC, philip-cline commented on lib/editor/actions/trip.js
> +      // Add default value to continuous pickup if not provided
Added in https://github.com/ibi-group/datatools-ui/pull/720/commits/c48bb1826bdeb075763a93734a394a61ed9ba3af

2021-09-22 16:27 UTC, philip-cline commented on lib/editor/actions/trip.js
> +      const tripCopy: any = (trip: any)
Cloned in https://github.com/ibi-group/datatools-ui/pull/720/commits/c48bb1826bdeb075763a93734a394a61ed9ba3af

2021-09-22 19:04 UTC, binh-dam-ibigroup approved these changes
LGTM, thank you for working on this.

2021-09-22 19:04 UTC, binh-dam-ibigroup commented
Passing this on to @miles-grant-ibigroup for review

2021-09-23 09:01 UTC, miles-grant-ibigroup approved these changes
Great patch! Well done finding that error.

2021-09-23 09:01 UTC, merged