fix(TimetableHeader): separate offset input into two inputs
ibi-group/datatools-ui pull request #817
Opened 2022-07-13 13:53 UTC by miles-grant-ibigroup

### Checklist

- [X] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [X] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [X] The description lists all applicable issues this PR seeks to resolve
- [X] The description lists any configuration setting(s) that differ from the default settings
- [X] All tests and CI builds passing

### Description

This PR refactors the offset input to be 2 separate textboxes. This removes the previous behavior in the unified textbox, which was seen by many to be confusing and complicated.

The input is now separated between hours and minutes.

<img width="233" alt="Screen Shot 2022-07-13 at 3 51 50 PM" src="https://user-images.githubusercontent.com/86619099/178750219-dd03df7d-94f4-4d25-8467-82461ffed6a8.png">

One piece of functionality I feel is missing is automatically moving to the minute input field, either after the user types a `:` or perhaps after they type two characters? Curious what others think about this.

2022-07-13 14:43 UTC, miles-grant-ibigroup commented
@philip-cline assigning this to you now, but since you're a more active datatools user than I am please let me know if the behavior is lacking/working unexpectedly and we can tweak this a little bit!

2022-07-13 15:15 UTC, philip-cline commented
I would definitely like to see the colon behaviour. I noted a few other things: 
- It would be nice to have "hh:mm" displayed as a placeholder when you first enter the timetable editor to indicate the input units. 
- I think some spacing between the inputs might look a bit better, with some corner rounding as well (perhaps on the offset button too). Something like: 
![image](https://user-images.githubusercontent.com/63798641/178769021-19f1f7e9-3df2-4f59-acec-7caec6af1963.png)

2022-07-14 13:16 UTC, philip-cline requested changes
Couple things:
- We could remove the border radius on the rightmost input box so it flows into the offset button. 
- Typing a # over 60 in the minutes box will convert to hours, but keep the value in the minutes box. So typing 120 for example adds 2 hours, but ends up as 2:120. 
- The placeholder is showing "hh:mn" right now, and is cut off a bit.

2022-07-14 14:04 UTC, miles-grant-ibigroup commented
What browser are you using to get the `hh:mn` bug? Everything else I can replicate but this is how the textbox renders for me in Safari, Firefox, and Chrome
<img width="153" alt="Screen Shot 2022-07-14 at 4 03 57 PM" src="https://user-images.githubusercontent.com/86619099/179001192-05a9aaae-b75d-49e1-af9b-dd4e40748ec7.png">

2022-07-14 14:39 UTC, philip-cline commented
Ok that was my bad, I needed to reload the CSS files. I'll give another review

2022-07-14 16:07 UTC, philip-cline approved these changes
Everything looks good and works well. Just a few small questions

2022-07-14 16:07 UTC, philip-cline commented on lib/editor/components/HourMinuteInput.js
> +import React, {Component, KeyboardEvent } from 'react'
```suggestion
import React, {Component, KeyboardEvent} from 'react'
```

2022-07-14 16:07 UTC, philip-cline commented on lib/editor/components/HourMinuteInput.js
> +          ref={'minuteInput'}
Is this `ref` used?

2022-07-14 17:22 UTC, miles-grant-ibigroup commented on lib/editor/components/HourMinuteInput.js
> +          ref={'minuteInput'}
It is not! Good catch thank you

2022-07-15 08:36 UTC, miles-grant-ibigroup commented on lib/editor/components/HourMinuteInput.js
> +          ref={'minuteInput'}
Removed in 886c24350363c7266590e2d0e17650e30bd43dc7

2022-07-19 00:14 UTC, daniel-heppner-ibigroup approved these changes
This feels like the best solution to me!

2022-07-19 10:19 UTC, merged