Avoid crash on failed projection
ibi-group/datatools-ui pull request #917
Opened 2023-03-01 19:39 UTC by philip-cline

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [ ] All tests and CI builds passing

### Description

Simple fix to avoid a bug associated with inserting stops into a pattern where the projection fails and places the stop at `spliceIndex` 0. A more robust fix will be coming in a forthcoming PR, which will resolve some other issues associated with the ✨ quirk ✨.

2023-03-01 19:56 UTC, miles-grant-ibigroup requested changes
Well done spotting that fix! Just one small cleanup suggestion

2023-03-01 19:56 UTC, miles-grant-ibigroup commented on lib/editor/actions/map/stopStrategies.js
> +        if (spliceIndex === 0) spliceIndex = 1
Can't we just initialize the splice index to 1?

2023-03-01 20:56 UTC, AdrianaCeric commented
![image](https://user-images.githubusercontent.com/62163307/222262940-cb0cc733-49ba-400b-98d5-d6688af55998.png)

2023-03-02 14:57 UTC, miles-grant-ibigroup approved these changes
Tested and works great! Thanks for this fix

2023-03-02 15:40 UTC, amy-corson-ibigroup approved these changes

2023-03-02 15:41 UTC, merged