Add stop headsigns for flex
ibi-group/datatools-ui pull request #925
Opened 2023-03-08 22:05 UTC by philip-cline

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Add stop headsigns for flex now too. GTFS-lib PR for testing: https://github.com/conveyal/gtfs-lib/pull/373

2023-03-09 19:32 UTC, miles-grant-ibigroup requested changes
Makes sense in theory but I have a quick question about the implementation

2023-03-09 19:32 UTC, miles-grant-ibigroup commented on lib/editor/components/pattern/PatternStopCard.js
> +    const patternStops = this.getPatternHaltsFromActivePattern()
Does this method exist?

2023-03-09 19:41 UTC, philip-cline commented on lib/editor/components/pattern/PatternStopCard.js
> +    const patternStops = this.getPatternHaltsFromActivePattern()
Resolved

2023-03-10 17:00 UTC, miles-grant-ibigroup approved these changes
Works well for me thanks for the changes

2023-03-13 17:27 UTC, binh-dam-ibigroup approved these changes
LGTM

2023-03-13 19:48 UTC, philip-cline commented
Awaiting backend PR merge

2023-03-14 19:41 UTC, merged