Don't Create Location Shape Points on Map Drag
ibi-group/datatools-ui pull request #940
Opened 2023-04-12 20:32 UTC by miles-grant-ibigroup

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Leaflet draw has a bug where when dragging the map, it receives both a touch and a click event, causing the map to both pan while a new point is added to a location shape. This behavior is confusing for users. The solution is to disable the leaflet touch event handler when a touch device is not present.

2023-04-13 15:07 UTC, philip-cline approved these changes
Wow amazing fix!!!! i can't believe it turned out to be this easy.

2023-04-21 16:21 UTC, binh-dam-ibigroup reviewed
What do you think about moving the prototype change outside of the component?

2023-04-21 16:21 UTC, binh-dam-ibigroup commented on lib/editor/components/map/EditorMap.js
> +    var originalOnTouch = L.Draw.Polyline.prototype._onTouch
```suggestion
    const originalOnTouch = L.Draw.Polyline.prototype._onTouch
```

2023-04-21 16:21 UTC, binh-dam-ibigroup commented on lib/editor/components/map/EditorMap.js
> +    var originalOnTouch = L.Draw.Polyline.prototype._onTouch
This is touching the prototype of a global object, therefore, I think this should be moved outside of the component code and run once for all. (There could be an undesired side effect the second time a map mounts.)

2023-04-21 20:08 UTC, binh-dam-ibigroup requested changes
I'm going to recommend moving the code that changes `L.Draw.Polyline.prototype._onTouch` outside of the component so it runs only once per browser load.

2023-04-24 18:08 UTC, philip-cline commented on lib/editor/components/map/EditorMap.js
> +    var originalOnTouch = L.Draw.Polyline.prototype._onTouch
Stuck it at the top of the file in https://github.com/ibi-group/datatools-ui/pull/940/commits/97525ab78f826293bc4ce997de0c8d5e4ba175f6. Let me know what you think

2023-04-24 18:32 UTC, binh-dam-ibigroup approved these changes
Latest change looks good, thanks.

2023-04-24 18:43 UTC, merged