Add gitter to readme
ibi-group/datatools-ui pull request #953
Opened 2023-05-16 16:21 UTC by philip-cline

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Adds reference to new Gitter space and standardizes some formatting.

2023-05-16 16:38 UTC, miles-grant-ibigroup requested changes
Can you please add the badge instead? Like https://github.com/opentripplanner/otp-react-redux/pull/898/files

2023-05-16 16:38 UTC, miles-grant-ibigroup commented on README.md
> +We have a Gitter chat room for the full TRANSIT-Data-Tools project where you can post questions and comments: https://matrix.to/#/#transit-data-tools:gitter.im.
Can you please add the badge instead

2023-05-16 16:48 UTC, philip-cline commented on README.md
> +We have a Gitter chat room for the full TRANSIT-Data-Tools project where you can post questions and comments: https://matrix.to/#/#transit-data-tools:gitter.im.
How about badge and link? https://github.com/ibi-group/datatools-ui/pull/953/commits/a6442d802e35be8c4c642115cfa9da460fbf75d5

2023-05-17 13:50 UTC, miles-grant-ibigroup approved these changes
Copy reads great pending link change

2023-05-17 13:50 UTC, miles-grant-ibigroup commented on README.md
> +We have a Gitter [space](https://matrix.to/#/#transit-data-tools:gitter.im) for the full TRANSIT-Data-Tools project where you can post questions and comments.
Can we replace the link with the `gitter.im` one?

2023-05-24 18:40 UTC, daniel-heppner-ibigroup approved these changes

2023-05-24 18:40 UTC, daniel-heppner-ibigroup commented on README.md
> +We have a Gitter [space](https://matrix.to/#/#transit-data-tools:gitter.im) for the full TRANSIT-Data-Tools project where you can post questions and comments.
plz make this the same link

2023-06-15 18:09 UTC, philip-cline commented on README.md
> +We have a Gitter [space](https://matrix.to/#/#transit-data-tools:gitter.im) for the full TRANSIT-Data-Tools project where you can post questions and comments.
Same link but matrix. done.

2023-06-26 23:29 UTC, merged