Shared Stops Support
ibi-group/datatools-ui pull request #977
Opened 2023-07-31 13:14 UTC by miles-grant-ibigroup

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing
### Description

This PR adds support for editing a project's shared stops config.

2023-08-09 17:06 UTC, philip-cline requested changes
Can we just do some i18n and then this looks good assuming that we are limiting this PR in scope to just editing shared stops. I am looking forward to seeing how we handle displaying the validation on the front end

2023-08-09 17:06 UTC, philip-cline commented on lib/manager/components/ProjectSettingsForm.js
> +                {/* TODO: on enter, textarea should NOT submit */}
I might add some weight to this `TODO` it feels a little strange hitting enter twice, but most interaction will be through copying and pasting or uploading a file so I don't think this is too serious.

2023-08-09 17:06 UTC, philip-cline commented on lib/manager/components/ProjectSettingsForm.js
> +                {/* TODO: Validate CSV? */}
We should validate the CSV at least with the basic validation we do for transformations. Maybe some shared classes here?

2023-08-09 17:06 UTC, philip-cline commented on lib/manager/components/ProjectSettingsForm.js
> +          <Panel.Heading><Panel.Title componentClass='h4'>Shared Stops</Panel.Title></Panel.Heading>
New text should be i18n'd please :)

2023-08-09 17:06 UTC, philip-cline commented on lib/manager/components/ProjectSettingsForm.js
> +                  placeholder='Shared stops config CSV'
i18n please :)

2023-08-16 18:46 UTC, miles-grant-ibigroup commented
Thanks @philip-cline , changes are addressed

2023-08-23 13:18 UTC, philip-cline approved these changes
LGTM. Tests just failing bc the language files are mismatched now?

2023-10-18 19:19 UTC, merged